DELETE FROM STUDENTS WHERE ID = 1;

INSERT INTO STUDENTS(ID, NAME, HEIGHT) VALUES (1, "AMIR", 179);
INSERT INTO STUDENTS(ID, NAME, HEIGHT) VALUES (2, "MARY", 153);
INSERT INTO STUDENTS(ID, NAME, HEIGHT) VALUES (3, "PETER", 168);

COMMIT;
